# Generated by Django 4.1.5 on 2023-01-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikapay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Address2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='PostalCode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='address1',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
