# Generated by Django 4.1.5 on 2023-01-27 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sikapay', '0002_alter_signup_address2_alter_signup_postalcode_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='user',
        ),
    ]
