# Generated by Django 4.1.5 on 2023-02-05 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sikapay', '0005_rename_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='Country',
            new_name='country',
        ),
    ]
