# Generated by Django 4.1.5 on 2023-02-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikapay', '0006_rename_country_table_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='Age',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='Phone_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
