# Generated by Django 4.1.5 on 2023-02-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikapay', '0007_table_age_table_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='table2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=500)),
            ],
        ),
    ]
