# Generated by Django 3.2.16 on 2023-02-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikapay', '0008_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_update_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('Phone_number', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('city', models.EmailField(max_length=40)),
                ('town', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('nationality', models.EmailField(max_length=40)),
                ('address1', models.CharField(max_length=20)),
                ('address2', models.CharField(max_length=20)),
                ('zip_code', models.EmailField(max_length=40)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
