# Generated by Django 4.1.5 on 2023-02-09 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sikapay', '0008_table2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='table2',
        ),
    ]
