# Generated by Django 3.2.16 on 2023-02-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikapay', '0009_auto_20230207_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_update_profile',
            name='city',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='client_update_profile',
            name='nationality',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='client_update_profile',
            name='zip_code',
            field=models.CharField(max_length=40),
        ),
    ]
