# Generated by Django 4.1.5 on 2023-02-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sikapay', '0010_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='Address2',
            new_name='address2',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Lastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Phone_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='PostalCode',
            new_name='postalCode',
        ),
    ]
