# Generated by Django 4.1.5 on 2023-02-23 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sikapay', '0011_rename_address2_table_address2_rename_age_table_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='business',
        ),
    ]
