# Generated by Django 4.1.5 on 2023-02-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=30)),
                ('contact_number', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=100)),
                ('streetaddress2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('postalcode', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('confirmpassword', models.CharField(max_length=30)),
            ],
        ),
    ]
